### ISSUE TITLE
推しAIユーザー入力フォーム実装

### ISSUE THREAD

**Issue by NozomiMiyake** [toshiki-anraku/AiOshiApp#6]
- ユーザーが設定する項目は以下。（以下、推し＝実際の推しの名前と置き換える）設定方法は、何かしらのformを使って設定。いつでも変更できるように、DBに保存→プロンプトに反映。
    - 推しが自身を示す一人称
        - 推しが自身を示す一人称はなんですか？（人によって違うかもしれないから入力させる）※必須※
    - 推しの呼び名
        - 推しの呼び名はなんですか？（人によって違うかもしれないから入力させる）※必須※
    - 推しがUserを示す二人称
        - あなたはなんて呼ばれたいですか？※必須※
    - 推しの口調
        - 推しの口調があれば書いてね！
    - 推しが使用しない言葉
        - 推しが使わない言葉があれば書いてね！
    - 推しとUserとの思い出に追加する質問項目
        - あなたと推しの思い出は？（リアルOR架空）
    - 推しとUserの関係性
        - あなたと推しの関係性はなんですか？（リアルOR架空）※必須※
    - 推しにしてほしいことに追加する質問項目
        - 推しAIに何をしてほしい？※必須※複数可※
    - 制約条件に追加する質問項目
        - 公式プロフィール以外の内容で、追加したい内容があれば書いてね！
    - 推しに使ってほしい言葉に追加する質問項目
        - 推しに言ってほしいことを書いてね！

GitHub PagesでHTTPメソッド送れるか？POST送信できるか、確認。
JSONどんなで送るか、共有。
リッチメニューの出し分けについてできるかどうか調査。
ドキュメントルート、指定されているところに置く。

**Comment by Hitomi-Shibata** [comment]
ユーザーが設定する項目はユーザーがいつでも見れる（UI可愛くする）

**Comment by Hitomi-Shibata** [comment]
下記少し追加しました

===推しに関する情報===
- ユーザーが設定する項目は以下。（以下、推し＝実際の推しの名前と置き換える）設定方法は、何かしらのformを使って設定。いつでも変更できるように、DBに保存→プロンプトに反映。
    - 推しが自身を示す一人称
        - 推しの一人称は何？（人によって違うかもしれないから入力させる）※必須※
    - 推しの呼び名
        - なんて呼んでる？（人によって違うかもしれないから入力させる）※必須※
    - 推しがUserを示す二人称
        - なんて呼ばれたい？※必須※
    - 推しの口調
        - わかるよね？！
    - 推しが使用しない言葉
        - 推しが使わない言葉があれば書いてね！
    - 推しのセリフ例
        - 好きならいっぱい書けるよね？！
    - 制約条件に追加する質問項目
        - 推しの情報をいっぱい入れてね！推しのことどのくらい言えるの？

===推し活の記録===
- 推し活の記録（理想はカレンダーアプリのUI）
    　- イベント名
    　- 日時
    　- 会場
    　- セトリ
    　- プレゼント
    　- 推しとの会話・MC（重みがつけれるフラグをつけて、一番重い3つ(仮)をプロンプトに使用。※デモ時は好きな会話を3つ入れてもらう）
    　- メモ
推しとの会話はプロンプトに入れ込む。デモ時は会話以外はなしでOK（最終的にカレンダーで振り返られるような形にしたい。）

===妄想(課金要素？)===
- 推しとUserの関係性
    - どんな関係になりたいの？（妄想）※必須※
- 推しにしてほしいことに追加する質問項目（妄想）
    - 推しAIに何してほしいの？※必須※複数可※
- 推しに使ってほしい言葉に追加する質問項目（妄想）
    - なんて言ってほしい？
- 推しとのシュチュエーション（妄想）
    - どんなシュチュエーションがいい？
- 推しとUserとの思い出に追加する質問項目
    - 推しとの思い出は？（妄想）

**Comment by NozomiMiyake** [comment]
自分用メモ
・以下の記事を参考にLIFF作成した
https://qiita.com/njn0te/items/53c4b19208924567af7b

**Comment by NozomiMiyake** [comment]
①ユーザー入力フォーム送信時にチャット画面にプロンプトが表示されないようにする
②ユーザー入力フォーム送信後に入力値をフォームに表示した状態にする。
（③ユーザー入力中に一時保存ボタンを押したら、GPTにプロンプトは送信されないが、保存されて入力値がフォームに表示された状態になる。）※③は優先順位低い

①と②を実装完了しましたので、一旦クローズします。
